#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Andrew Wong <wongadev@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='/usr/local/bin/vim'
export VISUAL='/usr/local/bin/vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_AU.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# cdpath=(
#   $cdpath
# )

path=(
  $HOME/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

export LESS='-i -R'

if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

# Uses /tmp instead of /tmp/$USER so that tmux works.
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

#
# Application Envs
#

# Path helper for mactex
eval `/usr/libexec/path_helper -s`

# Include command-line API tokens
if [[ -r "$HOME/.tokens" ]]; then
    source "$HOME/.tokens"
fi

# Init Node Version Manager
# Manually update path to reduce load time:
# https://github.com/creationix/nvm/issues/860
if [[ -s "/usr/local/opt/nvm/nvm.sh" ]]; then
  export NVM_DIR="$HOME/.nvm"
  source "/usr/local/opt/nvm/nvm.sh" --no-use
  path=(
    $HOME/.nvm/versions/node/v8.9.1/bin
    $path
  )
fi
