#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Andrew Wong <wongadev@gmail.com>
#

#
# Source Prezto.
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Disable flow control
#

setopt noflowcontrol

#
# Use better constrasting dir colours
#

if [[ -f "$HOME/.config/dir_colours" ]]; then
  eval $(dircolors -b "$HOME/.config/dir_colours")
fi

#
# Personalised key bindings
#

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -M viins '^N' down-line-or-beginning-search
bindkey -M viins '^P' up-line-or-beginning-search

#
# Aliases
#

alias fm="urxvtc -name filemgr -e ranger"
alias grep="grep --color=auto"
alias ix="curl -n -F 'f:1=<-' http://ix.io"
alias ls="ls -hFH --color=auto --group-directories-first"
alias lsp="ls++ --potsf"
alias ntfsmount="sudo ntfs-3g -o gid=100,fmask=113,dmask=002 /dev/sde1 /mnt/usb"
alias tm="urxvtc -name ircmailbt -e tmux attach-session -d -t 0"
alias qe="qemu-system-x86_64 -enable-kvm"
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"
alias usbmount="sudo mount -o gid=100,fmask=113,dmask=002 /dev/sde1 /mnt/usb"
alias usbumount="sudo umount /mnt/usb"
