#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Andrew Wong <wongadev@gmail.com>
#

#
# Source Prezto.
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Source fzf: a command-line fuzzy finder written in Go
#

if [[ -s "$HOME/.fzf.zsh" ]]; then
  source "$HOME/.fzf.zsh"
fi

#
# Use GNU for ls on OSX. gdircolors is installed via `brew install coreutils`.
#

if is-callable 'gdircolors'; then
  if [[ -s "$HOME/.dir_colors" ]]; then
    eval "$(gdircolors --sh "$HOME/.dir_colors")"
  else
    eval "$(gdircolors --sh)"
  fi
fi

#
# Disable flow control
#

setopt NO_FLOW_CONTROL

#
# Personalised key bindings
#

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey -M viins '^N' down-line-or-beginning-search
bindkey -M viins '^P' up-line-or-beginning-search
bindkey -M viins 'jj' vi-cmd-mode

#
# Aliases
#

# Frequently accessed directories
alias cdd="cd $HOME/dotfiles"
alias cdh="cd $HOME/dev/www/homestead"
alias cdu="cd $HOME/dev/www/ubuntu"

# Pastebins
alias ix="curl -n -F 'f:1=<-' http://ix.io"
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"

# Vagrant
alias vd="vagrant destroy"
alias vg="vagrant global-status"
alias vh="vagrant halt"
alias vp="vagrant provision"
alias vs="vagrant ssh"
alias vu="vagrant up"
alias vuh="vagrant up && vagrant halt"
alias vus="vagrant up && vagrant ssh"

# Other friendly shortcuts
alias ls='/usr/local/bin/gls --group-directories-first --color=auto --classify --human-readable'
alias tm="tmux attach-session -d -t 0"
alias vim="nvim"
alias vimdiff="nvim -d"
alias zf="$HOME/.composer/vendor/zendframework/zendframework1/bin/zf.sh"
